// layout
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'portopolio_one_hard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(montserrat.variable, 'antialiased')}>
        {children}
      </body>
    </html>
  );
}
